### ISSUE TITLE
Most patterns can't be loaded

### ISSUE THREAD

**Issue by JonIsPatented** [kastle-lab/commonsense-micropatterns#6]
When trying to load most patterns, an error is displayed instead: `The pattern could not be loaded as an OWLAPI OWLOntology: The OWL representation path 'csmodl/patterns/Back.ttl' could not be read as an input stream.`
The Air and Area patterns load correctly, but every other pattern I've tested has failed.

**Comment by threefinbdd** [comment]
PatternLibrary.java function getDataPropertyValues.

produces the path for input pattern files.  Some are represented with `modl/csmodl` others are just `csmodl`

**Comment by threefinbdd** [comment]
Sat down with Jon Cole and discovered the contents of the TTL files are not the cause.  The method to which an OWLLiteral is extracting the path of a TTL file is incorrectly getting generated or extracted.  In some file cases, the path appears as `modl/cs-modl/...` having scope of the title.  In other cases, the path appears as `cs-modl/...` not being within scope of the program.

Will continue to debug as a team with Jon Cole if issue is not resolvable from his debugging.

**Comment by threefinbdd** [comment]
Hackathon for solution scheduled for 10/7 at 2p

**Comment by threefinbdd** [comment]
Index Generator script corrected to correctly path the rooted folder of the modl libraries (allowing for a representation of csmodl, easy-ai, and modl, within the OWLRepresentation Pattern Path)

ComodIDE appends the resource folder name to this OWLRepresentation path per MODL.
